// src/servicios/datosAgenciaSimulada.ts
import { AgenciaBackData } from "./transformarAgenciaBackData";

export const datosAgenciaSimuladaBack: AgenciaBackData = {
  idAgencia: 3,
  nombre: "Alohados",
  logo: "/logo2.png",
  tipografia_agencia: "Verdana",
  color_tipografia_agencia: "#212121",
  color_fondo_app: "#F3F3F3",
  color_principal: "#6A0DAD",
  color_secundario: "#CBAEF0",
  color_terciario: "#3E0073",

  header_imagen_background: "/fondo-playa.jpg",
  header_imagen_background_opacidad: 0.2,
  header_video_background: "/video1.mp4",
  header_video_background_opacidad: 0.3,

  buscador_tipografia: "Verdana",
  buscador_tipografia_color: "#FFFFFF",
  buscador_tipografia_color_label: "#6A0DAD",
  buscador_inputColor: "#212121",
  buscador_inputFondoColor: "#FFFFFF",
  buscador_color_primario: "#6A0DAD",
  buscador_color_secundario: "#CBAEF0",
  buscador_color_terciario: "white",

  publicidad_existe: true,
  publicidad_titulo: "Ofertas imperdibles",
  publicidad_tipografia_color: "#6A0DAD",
  publicidad_color_primario: "#6A0DAD",
  publicidad_color_secundario: "#CBAEF0",
  publicidad_color_terciario: "#3E0073",
  publicidad_imagen_1: "paginaWeb/arboleda.jpg",
  publicidad_imagen_2: "paginaWeb/colombia.jpg",
  publicidad_imagen_3: "paginaWeb/rocas.jpg",

  tarjetas_titulo: "Destinos recomendados",
  tarjetas_tipografia: "Verdana",
  tarjetas_tipografia_color: "white",
  tarjetas_tipografia_color_titulo: "#6A0DAD",
  tarjetas_tipografia_color_contenido: "#555555",
  tarjetas_color_primario: "#6A0DAD",
  tarjetas_color_secundario: "#D6B7ED",
  tarjetas_color_terciario: "#3E0073",

  banner_registro_titulo: "Registrate y viajá con nosotros",
  banner_registro_tipografia_color: "#FFFFFF",
  banner_registro_color_primario: "#6A0DAD",
  banner_registro_color_secundario: "#CBAEF0",
  banner_registro_color_terciario: "#3E0073",

  quienes_somos_es: "Somos expertos en viajes por América del Sur.",
  quienes_somos_en: "We are travel experts in South America.",
  quienes_somos_pt: "Somos especialistas em viagens pela América do Sul.",

  footer_texto: "© 2025 Alohados - Todos los derechos reservados",
  footer_tipografia: "Verdana",
  footer_tipografia_color: "white",
  footer_facebook: "https://facebook.com/alohados",
  footer_twitter: "x",
  footer_instagram: "x",
  footer_whatsapp: "https://wa.me/5491123456789",
  footer_telefono: "+54 9 11 2345-6789",
  footer_email: "info@alojados.com",
  footer_direccion: "direccion",
  footer_ciudad: "Mendoza",
  footer_pais: "Argentina",
  footer_color_primario: "#6A0DAD",
  footer_color_secundario: "#CBAEF0",
  footer_color_terciario: "#2E005A",
};
